### ISSUE TITLE
sound issue

### ISSUE THREAD

**Issue by Jared54545** [NotAn127/SM64-PC-Port-WebGL#5]
I have an issue with the sound that the sounds will not play nor the music so everything is so quiet idk if it's Chrome or not but it's just so quiet (thanks for reading)

**Comment by Algiuxs** [comment]
highlight any text in the same tab as the game before the game starts, then you should hear the sound .
I know this sounds ridiculous, but trust me it works.

**Comment by NotAn127** [comment]
> I have an issue with the sound that the sounds will not play nor the music so everything is so quiet idk if it's Chrome or not but it's just so quiet (thanks for reading)

You can fix it by going to the site settings and go to sound and make it to where it says "always allow" in the sound option

**Comment by parkerlreed** [comment]
This doesn't work for Firefox

> An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page.

The page has to explicitly trigger audio based off a user interaction. Highlighting text does nothing.

**Comment by parkerlreed** [comment]
Ok so I had to highlight REALLY quickly before the game loaded. Only had about less than half a second to do it.

**Comment by Algiuxs** [comment]
> Ok so I had to highlight REALLY quickly before the game loaded. Only had about less than half a second to do it.

If it works, its fine.
